# device: "cuda" | "cpu"
device: cuda
debug_mode: false
imbalance: false
offset: true

# distributed networks
# users:            number of users
# random_sampling:   whether or not perform random sampling before each iteration
# sampling_fraction: the fraction of users to sample
# alpha:             the alpha parameter of the Dirichlet distribution 
rounds: 30
users: 30
iid: true
# iid: false
# alpha: 0.01
user_with_data: ""
# user_with_data: "/media/kaiyue/2D8A97B87FB4A806/Datasets/user_with_data/fmnist/user_dataidx_map_0.05.dat"
user_with_data: "/media/kaiyue/2D8A97B87FB4A806/Datasets/user_with_data/fmnist/user_dataidx_map_0.10.dat"
# user_with_data: "/media/kaiyue/2D8A97B87FB4A806/Datasets/user_with_data/fmnist/user_dataidx_map_1.00.dat"
# user_with_data: "/media/kaiyue/2D8A97B87FB4A806/Datasets/user_with_data/mnist/user_dataidx_map_0.10_0.dat"
# user_with_data: "/media/kaiyue/2D8A97B87FB4A806/Datasets/user_with_data/mnist/user_dataidx_map_0.05_0.dat"

# hyperparameters and model type
# model:            "naiveMLP", "naiveCNN"
# local_batch_size: size of the local batch
# tau:              number of local iterations
# gamma:            gamma parameter described in the paper 
# rounds:           total communication rounds upper bound
# momentum:         momentum settings for SGD  

# model: "naiveCNN"
# model: "naiveMLP"
model: "bn"
full_weight_dir: ""
full_weight_dir: "/media/kaiyue/2D8A97B87FB4A806/Datasets/heuristic/full_init.pth"
local_batch_size: 100
tau: 20
# lr: 0.0005
# lr: 0.05
lr: 0.0005
gamma: 1
momentum: 0
weight_decay: 1.e-10


# predictor: previous_frame | delta_step 
# quantization_level: (2*s + 1)
# combined_quantize: whether or not the MSB is 
#                   combined in the quantization  
quantization_level: 256
# quantization_level: 0
# quantizer: "plain"
# quantizer: "qsgd"
quantizer: "uniform"


# Simulation dataset configurations
# test_data_dir : the directory to the testDataset
# train_data_dir: the directory to the trainDataset
# sample_size:   the size of one sample [height x width/num_of_features]
# classes:      the number of classes
record_dir:     ../This{}.dat
# test_data_dir:  /media/kaiyue/2D8A97B87FB4A806/Datasets/mnist/test.dat
# train_data_dir: /media/kaiyue/2D8A97B87FB4A806/Datasets/mnist/train.dat
test_data_dir:  /media/kaiyue/2D8A97B87FB4A806/Datasets/fmnist/test.dat
train_data_dir: /media/kaiyue/2D8A97B87FB4A806/Datasets/fmnist/train.dat
sample_size:
- 28
- 28
channels: 1
classes: 10

# record_dir:     ../This{}.dat
# test_data_dir:  /media/kaiyue/2D8A97B87FB4A806/Datasets/cifar-10-python/test.dat
# train_data_dir: /media/kaiyue/2D8A97B87FB4A806/Datasets/cifar-10-python/train.dat
# sample_size:
# - 32
# - 32
# channels: 3
# classes: 10


# Log configurations
log_iters:   1
log_level:   "INFO"
log_file:    "./train.log"